server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8081
          predicates:
            - Path=/identity/**
          filters:
        - id: booking_service
          uri: http://localhost:8082
          predicates:
            - Path=/booking/**
        - id: hotel_service
          uri: http://localhost:8083
          predicates:
            - Path=/hotel/**
jwt:
  secret: cXWgolhZuRwCyI0mQGb1UtrtIrMLbpfL7TxvjghQnPi9M7NFU6o8Mp0Vk4s67s4T12wbuO84LbEsfuymJyzMeArr
