server:
  port: 8081
  servlet:
    context-path: /identity  # Sửa chính tả từ "indentity" thành "identity"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/identity_service  # Đổi sang PostgreSQL
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver  # Thêm driver cho PostgreSQL

  data:
    redis:
      host: localhost
      port: 6379          # cổng mặc định
      # password: yourRedisPassword   # bật dòng này nếu Redis yêu cầu mật khẩu

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Sử dụng dialect của PostgreSQL
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: cXWgolhZuRwCyI0mQGb1UtrtIrMLbpfL7TxvjghQnPi9M7NFU6o8Mp0Vk4s67s4T12wbuO84LbEsfuymJyzMeArr


